server:
  port: 8080
spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"